#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-only
"""Refresh actual build/test dependency licenses from pinned Go module sources."""
import argparse
import json
from pathlib import Path
import subprocess

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--project-license", type=Path, help="explicit maintenance-only full AGPL license source")
args = parser.parse_args()
root = Path(__file__).resolve().parents[1]
def run(*args):
    return subprocess.check_output(args, cwd=root, text=True)

modules = sorted(set(run("go", "list", "-deps", "-test", "-f", "{{if .Module}}{{.Module.Path}}{{end}}", "./...").split()) - {"memotrace/server"})
entries = [("Go " + run("go", "env", "GOVERSION").strip(), Path(run("go", "env", "GOROOT").strip()))]
for name in modules:
    module = json.loads(run("go", "list", "-m", "-json", name))
    entries.append((name + " " + module["Version"], Path(module["Dir"])))
out = ["# Third-party notices\n\nGenerated by `python3 scripts/dependency-notices.py` from the pinned build/test dependency graph.\nIncludes test-only JSON Schema validation dependencies. Original MemoTrace material remains AGPL-3.0-only.\n"]
for name, directory in entries:
    licenses = [directory / candidate for candidate in ("LICENSE", "LICENSE.txt", "LICENSE.md", "NOTICE") if (directory / candidate).is_file()]
    if not licenses:
        raise SystemExit(f"no license found: {name}")
    out.append(f"\n## {name}\n")
    for license_file in licenses:
        out.append(f"\n### {license_file.name}\n\n```text\n{license_file.read_text().rstrip()}\n```\n")
(root / "THIRD_PARTY_NOTICES.md").write_text("".join(out))
if args.project_license:
    license_bytes = args.project_license.read_bytes()
    if b"GNU AFFERO GENERAL PUBLIC LICENSE" not in license_bytes or len(license_bytes) < 30000:
        raise SystemExit("full AGPL license required")
    (root / "LICENSE").write_bytes(license_bytes)
print(f"Updated notices for Go and {len(modules)} pinned dependency modules.")
